### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by CopySloppy** [albertc44/peloton-coda-sync#6]
I receive this error when trying to use Google Apps Script. Any ideas where I went wrong?
![image](https://user-images.githubusercontent.com/104811537/166402088-626748e8-4b3c-4d5f-a20c-c078ab459d71.png)

**Comment by thealchen** [comment]
@CopySloppy This is most likely due to not entering in your Coda doc ID (see step 8 in the instructions) into the Google Apps Script. Make sure the doc ID is in between the two single quotes in the script. 

I'll be pushing out an update on this Peloton-Coda sync in the next few days as well. Stay tuned.
